Use C++14 to allow building for Electron 11 on MacOS
tree-sitter/node-tree-sitter pull request #83
Opened 2021-03-09 19:37 UTC by sergei-dyshel

Fixes https://github.com/tree-sitter/node-tree-sitter/issues/82.

2021-05-30 07:59 UTC, Symbolk commented
@maxbrunsfeld Could this be merged and released? A timely change for me.

2021-06-01 20:40 UTC, jinu-jang commented
This is just necessary for recent electron versions (v11, v12)
@sergei-dyshel thanks for the fix. This at least got me unblocked for now

2021-06-02 01:52 UTC, Symbolk commented
Right, for those who use electron v11+, here is the manual instruction to rebuild this module:

https://github.com/Symbolk/somanyconflicts#known-issues

2021-07-04 20:08 UTC, DeeDeeG commented
:+1:, and I think not merging this might slow progress on using Electron 11 in the Atom text editor. Might have to fork this package for Atom just to get it building in Electron 11.

2021-07-06 16:32 UTC, sadick254 commented
@maxbrunsfeld What could be holding back this PR from getting merged? As @DeeDeeG has stated this currently blocks Atom from upgrading to electron version 11.4.7.

2021-07-13 02:48 UTC, aminya requested changes
Why not c++17?

2021-07-13 02:48 UTC, aminya commented on binding.gyp
> +        'CLANG_CXX_LANGUAGE_STANDARD': 'c++14',
```suggestion
        'CLANG_CXX_LANGUAGE_STANDARD': 'c++17',
```

2021-09-02 01:36 UTC, Symbolk commented
After being torture by native module (node-gyp and electron-rebuild) for months, I finally switched to wasm of treesitter, and it seems working fine: https://github.com/Symbolk/somanyconflicts

Maybe this solution helps some of you.

2021-09-30 20:24 UTC, verhovsky commented
This PR can be closed because #92 (merged) did the same thing.

2021-10-01 06:42 UTC, closed without merging